### ISSUE TITLE
Can't do lein repl after fresh clone

### ISSUE THREAD

**Issue by jessicaappelbaum** [functional-koans/clojure-koans#111]
1) `git clone git://github.com/functional-koans/clojure-koans.git`
2) `lein repl`

```
Exception in thread "main" java.lang.RuntimeException: Unable to resolve symbol: do in this context, compiling:(/tmp/form-init4650606221399990463.clj:1:7462)
	at clojure.lang.Compiler.analyze(Compiler.java:6688)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler.eval(Compiler.java:6931)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Unable to resolve symbol: do in this context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler.resolveIn(Compiler.java:7164)
	at clojure.lang.Compiler.resolve(Compiler.java:7108)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7069)
	at clojure.lang.Compiler.analyze(Compiler.java:6648)
	... 20 more
REPL server launch timed out.
```

I am sure I'm doing something silly.

```
$ lein --version
Leiningen 2.6.1 on Java 1.8.0_91 Java HotSpot(TM) 64-Bit Server VM
```

**Comment by trptcolin** [comment]
Can you check in your `~/.lein/profiles.clj` for a `:repl-options` -> `:init` setting? I suspect there's something in there - and unfortunately our `:repl-options` / `:init` setting doesn't compose well between global settings and project-specific settings. I think it's totally reasonable to expect those to both work, and unfortunate that they don't (due to [this leiningen issue](https://github.com/technomancy/leiningen/issues/878)).

If my guess is right and you do find something in there, it should be fixed on master now (although it doesn't show up for me in the web UI yet).

**Comment by jessicaappelbaum** [comment]
Awesome, my repl is up and running! Thank you for your help!

**Comment by trptcolin** [comment]
Great, glad to hear it!
